sudo: false
language: perl
perl:
  - "5.20"
  - "5.18"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: alway
